### ISSUE TITLE
Create a release for the latest commit?

### ISSUE THREAD

**Issue by DanielWright** [boxen/phantomenv#5]
Hey guys,

Could you release the latest commit of this repo so https://github.com/boxen/puppet-phantomjs can be updated (specifically [these lines](https://github.com/boxen/puppet-phantomjs/blob/master/manifests/params.pp#L18-L19)) so Boxen'd phantomenv can work properly?

Thanks!

**Comment by rafaelfranca** [comment]
v0.0.9 tagged
